version: 2
jobs:
  build:
    working_directory: /dbc-demo1
    docker:
      - image: docker:17.05.0-ce-git
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.11.76
      - run:
          name: Build application Docker image
          command: |
            docker build -t dbc-demo1 .  
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login)
      - run:
          name: "Build & Push Docker Image"
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/dbc/demo1:latest -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/dbc/demo1:$CIRCLE_SHA1 .
            docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/dbc/demo1:$CIRCLE_SHA1
